/*
 * TP-3000 Taupunktspiegel-Hygrometer
 * Datei: TPlanguage.h
 * Zweck: Zentrales deutsch/englisches Sprachsystem der Benutzeroberflaeche.
 *
 * Copyright (C) 2025-2026 S. Brachtl (DK6WT)
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * Dieses Programm wird ohne jede Gewaehrleistung bereitgestellt.
 * Lizenz- und Herkunftsdetails: README.md und THIRD_PARTY_NOTICES.md
 */

//*********************************************************************************
//** TP-3000 Sprachsystem
//**
//** Ziel:
//** - Alle sichtbaren UI-Texte laufen schrittweise über TextId + T(...)
//** - Keine String-Klasse, keine dynamische Speicherverwaltung
//** - Optik bleibt erhalten: Positionen, Fonts, Farben und Boxen bleiben im Displaycode
//** - Sprache wird separat im EEPROM gespeichert, damit var_t unveraendert bleibt
//*********************************************************************************

#ifndef TPLANGUAGE_H
#define TPLANGUAGE_H

#include <Arduino.h>
#include <EEPROM.h>
#include "TP_T.h"

// -----------------------------------------------------------------------------
// Sprachen
// -----------------------------------------------------------------------------
enum LangId : uint8_t
{
  LANG_DE = 0,
  LANG_EN = 1,
  LANG_COUNT
};

// -----------------------------------------------------------------------------
// Text-IDs
// -----------------------------------------------------------------------------
enum TextId : uint16_t
{
  TXT_EMPTY,
  TXT_MAIN_TITLE,
  TXT_MAIN_T_MIRROR,
  TXT_MAIN_T_AMBIENT,
  TXT_MAIN_SETUP,
  TXT_MAIN_INFO,
  TXT_MAIN_STATUS_SAFETY,
  TXT_MAIN_STATUS_SD_LOGGING,
  TXT_MENU_MAIN_TITLE,
  TXT_MENU_CONTROL_PARAMETERS,
  TXT_MENU_FAN_SPEED,
  TXT_MENU_SENSOR_HEAD,
  TXT_MENU_CALIBRATION,
  TXT_MENU_CLOCK_DATE,
  TXT_MENU_DISPLAY_DIMMER,
  TXT_MENU_DISPLAY_MODE,
  TXT_MENU_FACTORY_RESET,
  TXT_MENU_LANGUAGE,
  TXT_MENU_INFO_LICENSE,
  TXT_MENU_INTERFACES,
  TXT_MENU_INTERFACES_TITLE,
  TXT_MENU_RS232_1,
  TXT_MENU_RS232_2,
  TXT_MENU_ETHERNET,
  TXT_MENU_USB,
  TXT_MENU_SD_CARD,
  TXT_MENU_FLOW_DISPLAY,
  TXT_MENU_ALMEMO,
  TXT_MENU_WINCONTROL,
  TXT_MENU_INTERFACES_PLACEHOLDER,
  TXT_MENU_CONTROL_TITLE,
  TXT_MENU_PID_KP,
  TXT_MENU_PID_KI,
  TXT_MENU_PID_KD,
  TXT_MENU_CONTROL_PERIOD,
  TXT_MENU_OPTIK_TARGET,
  TXT_MENU_FREIHEIZ_TEMP,
  TXT_MENU_AUTOCAL_INTERVAL,
  TXT_MENU_ADC_FILTER_MODE,
  TXT_MENU_ADC1_SFOCAL_MODE,
  TXT_MENU_CAL_TITLE,
  TXT_MENU_SIGNED_CALIBRATION,
  TXT_SIGNED_CAL_TITLE,
  TXT_SIGNED_CAL_STATUS,
  TXT_SIGNED_CAL_DEVICE_REQUEST,
  TXT_SIGNED_CAL_HEAD_REQUEST,
  TXT_SIGNED_CAL_DEVICE_IMPORT,
  TXT_SIGNED_CAL_HEAD_IMPORT,
  TXT_MENU_PT100_R0,
  TXT_MENU_PT100_2POINT,
  TXT_MENU_REF_100_120,
  TXT_MENU_TAUPOINT_OFFSET,
  TXT_MENU_MIRROR_PT100_2P,
  TXT_MENU_AMBIENT_PT100_2P,
  TXT_MENU_REF_100R,
  TXT_MENU_REF_120R,
  TXT_MENU_REF_EXT_AUTO,
  TXT_MENU_REF_VALUES,
  TXT_MENU_LANGUAGE_TITLE,
  TXT_LANGUAGE_DE,
  TXT_LANGUAGE_EN,
  TXT_BACK,
  TXT_SAVE,
  TXT_ENTER_SAVE,
  TXT_UP_DOWN_CHANGE,
  TXT_MENU_DISPLAY_DIMMER_TITLE,
  TXT_DISPLAY_MODE_TITLE,
  TXT_DISPLAY_MODE_MAIN_SCREEN,
  TXT_DISPLAY_MODE_HARDWARE_DIAG,
  TXT_DISPLAY_MODE_DIAG_OVERVIEW,
  TXT_DISPLAY_MODE_DIAG_DETAILS,
  TXT_DISPLAY_MODE_ADC_INFO,
  TXT_ADC_INFO_TITLE,
  TXT_ADC_INFO_STATUS,
  TXT_ADC_INFO_COMMAND,
  TXT_ADC_INFO_ANSWER,
  TXT_DIMMER_HINT,
  TXT_FMT_LEVEL_10,
  TXT_FMT_PWM,
  TXT_MENU_RTC_TITLE,
  TXT_FMT_RTC_DATE_TIME,
  TXT_RTC_ADJUST,
  TXT_RTC_STEP_DAY,
  TXT_RTC_STEP_MONTH,
  TXT_RTC_STEP_YEAR,
  TXT_RTC_STEP_HOUR,
  TXT_RTC_STEP_MIN_SAVE,
  TXT_RTC_NEXT,
  TXT_PID_KP_TITLE,
  TXT_PID_KI_TITLE,
  TXT_PID_KD_TITLE,
  TXT_PID_UPDOWN_1,
  TXT_PID_UPDOWN_0_1,
  TXT_MENU_CONTROL_PERIOD_TITLE,
  TXT_OPTIK_TARGET_TITLE,
  TXT_FREIHEIZ_TEMP_TITLE,
  TXT_AUTOCAL_INTERVAL_TITLE,
  TXT_ADC_FILTER_MODE_TITLE,
  TXT_ADC1_SFOCAL_MODE_TITLE,
  TXT_MENU_PT100_2POINT_TITLE,
  TXT_TITLE_MIRROR_PT100_2POINT,
  TXT_TITLE_AMBIENT_PT100_2POINT,
  TXT_PT100_SET1,
  TXT_PT100_ACT1,
  TXT_PT100_SET2,
  TXT_PT100_ACT2,
  TXT_LABEL_DIGIT,
  TXT_PT100_DIGIT_10,
  TXT_PT100_DIGIT_1,
  TXT_PT100_DIGIT_0_1,
  TXT_PT100_DIGIT_0_01,
  TXT_PT100_DIGIT_0_001_NEXT,
  TXT_ERR_PT100_DISTANCE,
  TXT_UP_DOWN_ENTER_NEXT,
  TXT_MENU_SENSOR_SELECT_R0_TITLE,
  TXT_MENU_SENSOR_R0_TITLE,
  TXT_SENSOR_MIRROR_PT100,
  TXT_SENSOR_AMBIENT_PT100,
  TXT_SENSOR_ITEM_MIRROR_PT100,
  TXT_SENSOR_ITEM_AMBIENT_PT100,
  TXT_DIGIT_INTEGER,
  TXT_DIGIT_0_1000,
  TXT_DIGIT_0_0100,
  TXT_DIGIT_0_0010,
  TXT_DIGIT_0_0001_SAVE,
  TXT_MENU_REFERENCES_TITLE,
  TXT_REF100_TITLE,
  TXT_REF120_TITLE,
  TXT_REF_VALUES_TITLE,
  TXT_REF_EXT_AUTO_TITLE,
  TXT_TAUPOINT_OFFSET_TITLE,
  TXT_DIGIT_0_001_SAVE,
  TXT_FMT_VALUE_OHM,
  TXT_ERR_REF_ORDER,
  TXT_FACTORY_TITLE,
  TXT_FACTORY_YES,
  TXT_FACTORY_NO,
  TXT_FACTORY_DONE,
  TXT_FACTORY_REBOOT,
  TXT_SENSOR_HEAD_TITLE,
  TXT_SENSOR_HEAD_LOAD,
  TXT_SENSOR_HEAD_SERIAL_NEXT,
  TXT_SERIAL_TITLE_FMT,
  TXT_SERIAL_DUMMY_NOTE,
  TXT_FAN_SPEED_TITLE,
  TXT_FMT_FAN_PERCENT,
  TXT_FMT_PWM_4095,
  TXT_FAN_UPDOWN,
  TXT_DEBUG_TITLE,
  TXT_DEBUG_R_PT100_MIRROR,
  TXT_DEBUG_R_PT100_AMBIENT,
  TXT_DEBUG_REF_100R,
  TXT_DEBUG_REF_120R,
  TXT_DEBUG_LED_CURRENT_SET,
  TXT_DEBUG_PELTIER_PWM_SET,
  TXT_DEBUG_FLOW_PHASE,
  TXT_DEBUG_PHASE_NORMAL,
  TXT_DEBUG_PHASE_HEAT_MIRROR,
  TXT_DEBUG_PHASE_LED_AUTOCAL,
  TXT_BOOT_PRODUCT_TITLE,
  TXT_BOOT_VERSION_LABEL,
  TXT_BOOT_DATE_LABEL,
  TXT_BOOT_DEVICE_SN_FMT,
  TXT_BOOT_HEAD_LABEL,
  TXT_BOOT_HEAD_SERIAL_FMT,
  TXT_BOOT_FIRMWARE_AUTHOR,
  TXT_BOOT_BASED_ON,
  TXT_DISPLAY_LOOP_DEBUG_MENU,
  TXT_DISPLAY_LOOP_DEBUG_TITLE,
  TXT_LOOP_DEBUG_OFF,
  TXT_LOOP_DEBUG_ON,
  TXT_ETH_INIT_MESSAGE,
  TXT_PLEASE_WAIT,
  TXT_MENU_ALARM,
  TXT_MENU_ALARM_TITLE,
  TXT_ALARM_MODE,
  TXT_ALARM_MODE_TITLE,
  TXT_ALARM_MODE_OFF,
  TXT_ALARM_MODE_LIMIT,
  TXT_ALARM_MODE_RANGE,
  TXT_ALARM_TAU_LOW,
  TXT_ALARM_TAU_HIGH,
  TXT_ALARM_RH_LOW,
  TXT_ALARM_RH_HIGH,
  TXT_ALARM_BUZZER,
  TXT_ALARM_BUZZER_TITLE,
  TXT_ALARM_BUZZER_OFF,
  TXT_ALARM_BUZZER_ON,
  TXT_ALARM_TOUCH_ACK,
  TXT_STATUS_INIT,
  TXT_STATUS_ERROR,
  TXT_STATUS_LIMIT,
  TXT_STATUS_SAFETY_STOP,
  TXT_STATUS_PREHEAT,
  TXT_STATUS_AUTOCAL,
  TXT_STATUS_SETTLING,
  TXT_STATUS_STABLE,
  TXT_STATUS_REF_OLD,
  TXT_STATUS_REF_ERROR,
  TXT_MENU_OUTPUT_INTERVAL,
  TXT_MENU_OUTPUT_FILTER,
  TXT_MENU_SD_WRITE,
  TXT_MENU_DIAGNOSTIC_DATA,
  TXT_MENU_STATUS_INFO,
  TXT_MAIN_CHART_HUMIDITY,
  TXT_MAIN_CHART_DEW_POINT,
  TXT_MAIN_CHART_T_POINT,
  TXT_MAIN_CHART_NOW,
  TXT_MENU_DEVICE_STORAGE,
  TXT_DEVICE_STORAGE_TITLE,
  TXT_DEVICE_STORAGE_STATUS,
  TXT_DEVICE_SETTINGS_LOAD,
  TXT_DEVICE_FACTORY_CAL_LOAD,
  TXT_DEVICE_SETTINGS_SAVE,
  TXT_DEVICE_FACTORY_CAL_SAVE,
  TXT_DEVICE_FACTORY_RESET,
  TXT_DEVICE_STORAGE_STATUS_TITLE,
  TXT_DEVICE_STORAGE_SETTINGS_PREP,
  TXT_DEVICE_STORAGE_FACTORY_PREP,
  TXT_DEVICE_STORAGE_NO_CHANGE,
  TXT_DEVICE_STORAGE_FACTORY_SCOPE,
  TXT_DEVICE_STORAGE_HEAD_SCOPE,
  TXT_DEVICE_STORAGE_ENTER_BACK,
  TXT_DEVICE_STORAGE_DEVICE_SN_FMT,
  TXT_DEVICE_STORAGE_HEAD_FMT,
  TXT_DISPLAY_MAIN_LAYOUT_MENU,
  TXT_DISPLAY_MAIN_LAYOUT_TITLE,
  TXT_DISPLAY_MAIN_LAYOUT_STANDARD,
  TXT_DISPLAY_MAIN_LAYOUT_THREE_VALUES,
  TXT_MENU_CAL_CERT_QR,
  TXT_COUNT
};

// Globale Spracheinstellung aus der Hauptdatei.
extern uint8_t ui_language;

// Sprache liegt ab EEPROM V12 im A/B-gesicherten Device-/UI-Settings-Block.
// Die Inline-Funktionen bleiben als Kompatibilitaetswrapper fuer den bestehenden
// Code erhalten.
static inline void uiLanguageLoad()
{
  tpDeviceUiConfigLoad();
}

static inline void uiLanguageSave()
{
  if (ui_language >= LANG_COUNT)
  {
    ui_language = LANG_DE;
  }
  tpDeviceUiConfigSave();
}

// -----------------------------------------------------------------------------
// Texttabelle
// -----------------------------------------------------------------------------
static const char* const textTable[LANG_COUNT][TXT_COUNT] =
{
  // ---------------------------------------------------------------------------
  // DEUTSCH
  // ---------------------------------------------------------------------------
  {
    "",
    "          TAUPUNKTSPIEGEL HYGROMETER",
    "T-Spiegel :",
    "T-Umgebung:",
    "SETUP",
    "INFO",
    "Safety",
    "SD-Logging",
    "--- TAUPUNKTSPIEGEL SETUP ---",
    "Regelparameter",
    "Fan-Speed",
    "Sensorkopf",
    "Kalibrierung",
    "Uhr/Datum",
    "Display Dimmer",
    "Anzeige",
    "Werkseinstellung",
    "Sprache",
    "Lizenzen / Marken",
    "Schnittstellen",
    "--- SCHNITTSTELLEN ---",
    "RS232-1",
    "RS232-2",
    "Ethernet",
    "USB",
    "SD-Karte",
    "Zusatzanzeige",
    "ALMEMO",
    "WinControl-Ausgabe",
    "Vorbereitung - Funktion folgt",
    "--- REGELPARAMETER ---",
    "PID Kp-Verstärkung",
    "PID Ki-Integral",
    "PID Kd-Dämpfung",
    "Regelungs-Takt",
    "Optik-Zielwert",
    "Freiheiztemperatur",
    "Auto-Cal Intervall",
    "Messfilter",
    "ADC1 SFOCAL",
    "--- KALIBRIERUNG ---",
    "Signierte Kalibrierung",
    "--- SIGNIERTE KALIBRIERUNG ---",
    "Info / Gültigkeit",
    "Geräte-Anfrage auf SD",
    "Kopf-Anfrage auf SD",
    "Gerätefreigabe importieren",
    "Kopfzertifikat importieren",
    "Pt100 R0",
    "Pt100 2-Punkt",
    "Ref Low / High",
    "Taupunkt Offset",
    "Spiegel Pt100 2P",
    "Umgebung Pt100 2P",
    "Ref Low",
    "Ref High",
    "Ext-Ref Auto",
    "Ref-/Kanalwerte",
    "--- SPRACHE / LANGUAGE ---",
    "Deutsch",
    "English",
    "Zurück",
    "Speichern",
    "ENTER: speichern",
    "UP/DOWN ändern",
    "--- DISPLAY HELLIGKEIT ---",
    "--- ANZEIGE ---",
    "Hauptscreen",
    "Hardware Diagnose",
    "Diag 1 Übersicht",
    "Diag 2 Details",
    "ADC Info",
    "ADC INFO",
    "Status:",
    "Befehl:",
    "Antwort:",
    "UP heller / DOWN dunkler",
    "Stufe: %2u / 10",
    "PWM: %3u",
    "--- RTC UHRZEIT EINSTELLEN ---",
    "Datum: %02d.%02d.%04d | Zeit: %02d:%02d",
    "Justiere aktuell: ",
    "[ TAG ]",
    "[ MONAT ]",
    "[ JAHR ]",
    "[ STUNDE ]",
    "[ MINUTE ]>Speichern",
    "Tippe [ENTER] für weiter",
    "--- PID Verstärkung (Kp) ---",
    "--- PID INTEGRAL (Ki) ---",
    "--- PID Dämpfung (Kd) ---",
    "UP/DOWN: +/- 1",
    "UP/DOWN: +/- 0.1",
    "--- REGELLOOP TAKTZEIT ---",
    "--- OPTIK-ZIELWERT ---",
    "--- FREIHEIZTEMPERATUR ---",
    "--- AUTO-CAL INTERVALL ---",
    "--- MESSFILTER ---",
    "--- ADC1 SFOCAL ---",
    "--- PT100 2-PUNKT ---",
    "--- SPIEGEL PT100 2-PUNKT ---",
    "--- UMGEBUNG PT100 2-PUNKT ---",
    "Soll1",
    "Ist1",
    "Soll2",
    "Ist2",
    "Stelle: ",
    "[10.000]",
    "[ 1.000]",
    "[ 0.100]",
    "[ 0.010]",
    "[ 0.001] -> weiter",
    "FEHLER: Abstand min. 30.000 °C",
    "UP/DOWN ändern, ENTER weiter",
    "--- SENSOR AUSWAHL R0 ---",
    "--- SENSOR EICHUNG R0 ---",
    "Spiegel Pt100",
    "Umgebung Pt100",
    "1. Spiegel Pt100",
    "2. Umgebung Pt100",
    "[ VORKOMMA ]",
    "[ 0.1000 ]",
    "[ 0.0100 ]",
    "[ 0.0010 ]",
    "[ 0.0001 ] -> Speichern",
    "--- REFERENZEN ---",
    "--- REF LOW EICHUNG ---",
    "--- REF HIGH EICHUNG ---",
    "--- REF-/KANALWERTE ---",
    "--- EXT-REF ABGLEICH ---",
    "--- TAUPUNKT OFFSET ---",
    "[ 0.001 ] -> Speichern",
    "Wert: %3ld.%05ld \xB1",
    "FEHLER: Ref High muss > Ref Low sein",
    "--- RESET TO DEFAULT? ---",
    "Ja - Ausführen",
    "Nein - Abbrechen",
    "Werkseinstellungen geladen.",
    "Reboot läuft...",
    "--- SENSOR-KOPF ---",
    "ENTER: Kopfprofil laden",
    "Danach Seriennummer wählen",
    "--- SERIEN NR. %s ---",
    "Dummy: Kalibrierwerte später SD",
    "--- Lüfter-Speed ---",
    "Lüfter: %u %%",
    "PWM: %u / 4095",
    "UP/DOWN: 1 %",
    "METROLOGIE - HARDWARE DIAGNOSE",
    "R-Pt100 Spiegel : ",
    "R-Pt100 Umgebung: ",
    "Platinen-Ref Low: ",
    "Platinen-Ref High:",
    "LED-Strom Vorgabe: ",
    "Peltier PWM-Stell: ",
    "Ablauf Phase     : ",
    "0 [NORMALER MESSBETRIEB]",
    "1 [SPIEGEL FREIHEIZEN]",
    "2 [LED-Autoeichung läuft]",
    "Taupunktspiegel",
    "Version   = ",
    "Date      = ",
    "Ger\xB2t-SN = %s",
    "Head      = ",
    "H-Serial  = %05lu",
    "Firmware S. Brachtl - GNU GPLv3-only",
    "based on LJ-2000M code structures by L. Jonasson & J.G. Holstein",
    "Loop Hz/Max Anzeige",
    "--- LOOP-ANZEIGE ---",
    "Aus",
    "Ein",
    "Ethernet Initialisierung...",
    "Bitte warten...",
    "Alarm",
    "--- ALARM ---",
    "Alarm Modus",
    "--- ALARM MODUS ---",
    "Aus",
    "Grenzwert",
    "Bereich",
    "Taupunkt min",
    "Taupunkt max",
    "\xB5""rH min",
    "\xB5""rH max",
    "Buzzer",
    "--- ALARM BUZZER ---",
    "Aus",
    "Ein",
    "Alarmfeld antippen =",
    "INIT",
    "FEHLER",
    "GRENZWERT",
    "STOP",
    "FREIHEIZEN",
    "AUTO-CAL",
    "REGELT",
    "STABIL",
    "REF ALT",
    "REF FEHLER",
    "Ausgabe Intervall",
    "Ausgabe Filter",
    "SD Schreiben",
    "Diagnose Daten",
    "Status Information",
    "Feuchte",
    "Taupunkt",
    "T-Punkt",
    "Jetzt",
    "Geräte-Speicher",
    "--- GERÄTE-SPEICHER ---",
    "Speicherstatus",
    "Einstellungen laden",
    "Werksjustierung laden",
    "Einstellungen speichern",
    "Werksjustierung speichern",
    "Werkseinstellung Reset",
    "--- SPEICHERSTATUS ---",
    "Einstellungs-Speicher vorbereitet",
    "Werksjustierung vorbereitet",
    "Noch keine Daten geändert",
    "Werksjustierung = Grundgerät",
    "",
    "ENTER: zurück",
    "Gerät: %s",
    "Kopf: %s SN %05lu",
    "Hauptscreen Layout",
    "--- HAUPTSCREEN LAYOUT ---",
    "2 Werte",
    "3 Werte",
    "Kalibrierschein anzeigen"
  },

  // ---------------------------------------------------------------------------
  // ENGLISCH
  // ---------------------------------------------------------------------------
  {
    "",
    "         DEW POINT MIRROR HYGROMETER",
    "T-Mirror  :",
    "T-Ambient :",
    "SETUP",
    "INFO",
    "Safety",
    "SD-Logging",
    "--- DEW POINT MIRROR SETUP ---",
    "Control parameters",
    "Fan speed",
    "Sensor head",
    "Calibration",
    "Clock/Date",
    "Display dimmer",
    "Display mode",
    "Factory reset",
    "Language",
    "Licenses / Trademarks",
    "Interfaces",
    "--- INTERFACES ---",
    "RS232-1",
    "RS232-2",
    "Ethernet",
    "USB",
    "SD card",
    "Additional display",
    "ALMEMO",
    "WinControl output",
    "Preparation - function follows",
    "--- CONTROL PARAMETERS ---",
    "PID Kp gain",
    "PID Ki integral",
    "PID Kd damping",
    "Control period",
    "Optical target",
    "Heat-clean temp",
    "Auto-cal interval",
    "Measurement filter",
    "ADC1 SFOCAL",
    "--- CALIBRATION ---",
    "Signed calibration",
    "--- SIGNED CALIBRATION ---",
    "Info / validity",
    "Device request to SD",
    "Head request to SD",
    "Import device approval",
    "Import head certificate",
    "Pt100 R0",
    "Pt100 2-point",
    "Ref Low / High",
    "Dew point offset",
    "Mirror Pt100 2P",
    "Ambient Pt100 2P",
    "Ref Low",
    "Ref High",
    "Ext ref auto",
    "Ref/channel values",
    "--- LANGUAGE / SPRACHE ---",
    "Deutsch",
    "English",
    "Back",
    "Save",
    "ENTER: save",
    "UP/DOWN change",
    "--- DISPLAY BRIGHTNESS ---",
    "--- DISPLAY MODE ---",
    "Main screen",
    "Hardware diagnosis",
    "Diag 1 overview",
    "Diag 2 details",
    "ADC info",
    "ADC INFO",
    "Status:",
    "Command:",
    "Answer:",
    "UP brighter / DOWN darker",
    "Level: %2u / 10",
    "PWM: %3u",
    "--- SET RTC CLOCK ---",
    "Date: %02d.%02d.%04d | Time: %02d:%02d",
    "Adjust: ",
    "[ DAY ]",
    "[ MONTH ]",
    "[ YEAR ]",
    "[ HOUR ]",
    "[ MINUTE ]->Save",
    "Tap [ENTER] for next",
    "--- PID GAIN (Kp) ---",
    "--- PID INTEGRAL (Ki) ---",
    "--- PID DAMPING (Kd) ---",
    "UP/DOWN: +/- 1",
    "UP/DOWN: +/- 0.1",
    "--- CONTROL LOOP PERIOD ---",
    "--- OPTICAL TARGET ---",
    "--- HEAT-CLEAN TEMPERATURE ---",
    "--- AUTO-CAL INTERVAL ---",
    "--- MEASUREMENT FILTER ---",
    "--- ADC1 SFOCAL ---",
    "--- PT100 2-POINT ---",
    "--- MIRROR PT100 2-POINT ---",
    "--- AMBIENT PT100 2-POINT ---",
    "Set1",
    "Act1",
    "Set2",
    "Act2",
    "Digit: ",
    "[10.000]",
    "[ 1.000]",
    "[ 0.100]",
    "[ 0.010]",
    "[ 0.001] -> next",
    "ERROR: distance min. 30.000 °C",
    "UP/DOWN change, ENTER next",
    "--- SENSOR SELECT R0 ---",
    "--- SENSOR R0 CALIBRATION ---",
    "Mirror Pt100",
    "Ambient Pt100",
    "1. Mirror Pt100",
    "2. Ambient Pt100",
    "[ INTEGER ]",
    "[ 0.1000 ]",
    "[ 0.0100 ]",
    "[ 0.0010 ]",
    "[ 0.0001 ] -> Save",
    "--- REFERENCES ---",
    "--- REF LOW CALIBRATION ---",
    "--- REF HIGH CALIBRATION ---",
    "--- REF/CHANNEL VALUES ---",
    "--- EXT REF CALIBRATION ---",
    "--- DEW POINT OFFSET ---",
    "[ 0.001 ] -> Save",
    "Value: %3ld.%05ld \xB1",
    "ERROR: Ref High must be > Ref Low",
    "--- RESET TO DEFAULT? ---",
    "Yes - Execute",
    "No - Cancel",
    "Factory defaults loaded.",
    "Rebooting...",
    "--- SENSOR HEAD ---",
    "ENTER: load head profile",
    "Then select serial number",
    "--- SERIAL NO. %s ---",
    "cal data later on SD",
    "--- FAN SPEED ---",
    "Fan: %u %%",
    "PWM: %u / 4095",
    "UP/DOWN: 1 %",
    "METROLOGY - HARDWARE DIAGNOSIS",
    "R-Pt100 mirror : ",
    "R-Pt100 ambient: ",
    "Board ref Low : ",
    "Board ref High: ",
    "LED current set: ",
    "Peltier PWM set: ",
    "Process phase  : ",
    "0 [NORMAL MEASUREMENT]",
    "1 [MIRROR HEAT-CLEAN]",
    "2 [LED AUTO-CAL RUNNING]",
    "Dew point mirror",
    "Version   = ",
    "Date      = ",
    "Device SN = %s",
    "Head      = ",
    "H-Serial  = %05lu",
    "Firmware S. Brachtl - GNU GPLv3-only",
    "based on LJ-2000M code structures by L. Jonasson & J.G. Holstein",
    "Loop Hz/Max display",
    "--- LOOP DISPLAY ---",
    "Off",
    "On",
    "Ethernet initialization...",
    "Please wait...",
    "Alarm",
    "--- ALARM ---",
    "Alarm mode",
    "--- ALARM MODE ---",
    "Off",
    "Limit",
    "Range",
    "Dew point min",
    "Dew point max",
    "\xB5""rH min",
    "\xB5""rH max",
    "Buzzer",
    "--- ALARM BUZZER ---",
    "Off",
    "On",
    "Tap alarm field =",
    "INIT",
    "ERROR",
    "LIMIT",
    "STOP",
    "PREHEAT",
    "AUTO-CAL",
    "SETTLING",
    "STABLE",
    "REF OLD",
    "REF ERROR",
    "Output Interval",
    "Output Filter",
    "SD Write",
    "Diagnostic Data",
    "Status Information",
    "Humidity",
    "Dew point",
    "D-point",
    "  Now",
    "Device storage",
    "--- DEVICE STORAGE ---",
    "Storage status",
    "Load settings",
    "Load factory calibration",
    "Save settings",
    "Save factory calibration",
    "Factory reset",
    "--- STORAGE STATUS ---",
    "Settings storage prepared",
    "Factory calibration prepared",
    "No data changed yet",
    "Factory calibration = base unit",
    "Head data later from SD",
    "ENTER: back",
    "Device: %s",
    "Head: %s SN %05lu",
    "Main screen layout",
    "--- MAIN SCREEN LAYOUT ---",
    "2 values",
    "3 values",
    "Show calibration QR"
  }
};

// -----------------------------------------------------------------------------
// Zugriffsfunktion
// -----------------------------------------------------------------------------
static inline const char* T(TextId id)
{
  uint8_t lang = ui_language;

  if (lang >= LANG_COUNT)
  {
    lang = LANG_DE;
  }

  if (id >= TXT_COUNT)
  {
    return "?";
  }

  const char* text = textTable[lang][id];
  if (text == nullptr)
  {
    return "?";
  }

  return text;
}

#endif // TPLANGUAGE_H
